services:
  app:
    image: ghcr.io/tbxark/registry-sync:latest
    pull_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/root/.docker/config.json
      - ./config.json:/config.json
    restart: always
    command: ["--config", "/config.json"]
