services:
  app:
    image: ghcr.io/tbxark/registry-sync:latest
    pull_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    restart: always
